### ISSUE TITLE
Feature request: Indicate current date

### ISSUE THREAD

**Issue by Ziron** [WeMakeMachines/joplin-plugin-event-calendar#1]
First, great plugin! The flexible grouping is just what I was missing from the Life Calendar!

Would it be possible to add an option to indicate the current date in the calendar? This would make it easier to get an overview of how long it was since the last event.
I can achieve this by manually adding todays date as an event so that the end of the calendar extends, but it would be nice to have it updating automatically.
If there are future events added beyond todays date it would also be nice to have the current date marked, possibly also with the option to have past and future dates styled differently just as the Life Calendar does?

I could probably implement this if you want help with the development.

Thanks again!

**Comment by WeMakeMachines** [comment]
That sounds like a great idea. And yeah, it makes sense to implement this feature rather than trying those costly workarounds. Yeah sure I'll definitely add this in, though if you want a challenge, you can give it a shot :smile:

**Comment by WeMakeMachines** [comment]
Hey I just added the feature. Actually it gave me a chance to refactor the renderer.
